/** DESKTOP ONLY — compatibility re-exports for the unified auth bootstrap flow. */

export {
    assertDesktopRelativeApiPath,
    canRenderDesktopApplicationShell,
    createDesktopAuthenticatedFetch,
    createDesktopAuthBootstrapRuntime,
    createDesktopProtectedActionClient,
    DESKTOP_BOOTSTRAP_LOG_PREFIX,
    DESKTOP_PROTECTED_ACTION_HEADER_TOO_LARGE_STATUS,
    diagnoseDesktopShellGate,
    hasValidDesktopSupabaseSession,
    resolveDesktopAuthenticatedCredentials,
    runDesktopRemoteBootstrap,
    SESSION_EXPIRED_MESSAGE,
    startDesktopLocalBootstrap,
    traceBootstrapStep,
    waitForDesktopApiCredentials,
    type DesktopAuthBootstrapConfig,
    type DesktopAuthRequestMode,
    type DesktopAuthTransport,
    type DesktopAuthenticatedCredentials,
    type DesktopAuthenticatedFetch,
    type DesktopAuthenticatedFetchInit,
    type DesktopAuthenticatedRequestConfig,
    type DesktopBootstrapStep,
    type DesktopProtectedActionClientConfig,
    type DesktopProtectedActionFetch,
    type DesktopProtectedActionFetchInit,
    type DesktopRemoteBootstrapActions,
    type DesktopRemoteBootstrapResult,
    type DesktopShellGateDecision,
    type DesktopShellGateInput,
} from "./desktop-auth-bootstrap-flow";
