/** DESKTOP ONLY — compatibility re-exports for the unified auth bootstrap flow. */

export {
    canRenderDesktopApplicationShell,
    DESKTOP_AUTH_BOOTSTRAP_MARKERS,
    DESKTOP_AUTH_RATE_LIMIT_MESSAGE,
    DESKTOP_BOOTSTRAP_LOG_PREFIX,
    diagnoseDesktopShellGate,
    ensureDesktopAuthenticatedSession,
    isDesktopApiReady,
    isDesktopAuthenticatedSessionReady,
    isDesktopAuthenticatedShellReady,
    isDesktopAuthSessionBootstrapComplete,
    isDesktopAuthSessionBootstrapSettled,
    isDesktopAuthBootstrapRateLimited,
    markDesktopAuthSignInPending,
    resetDesktopAuthSessionBootstrap,
    runDesktopAuthBootstrap,
    runDesktopRemoteBootstrap,
    startDesktopAuthSessionBootstrap,
    startDesktopLocalBootstrap,
    traceBootstrapStep,
    waitForDesktopAuthenticatedSession,
    type DesktopAuthBootstrapConfig,
    type DesktopAuthBootstrapOutcome,
    type DesktopAuthSessionBootstrapOptions,
    type DesktopBootstrapStep,
    type DesktopRemoteBootstrapActions,
    type DesktopRemoteBootstrapResult,
    type DesktopShellGateDecision,
    type DesktopShellGateInput,
} from "./desktop-auth-bootstrap-flow";

export {
    clearDesktopApiCredentials,
    clearDesktopAuthenticatedSession,
    DESKTOP_API_READY_EVENT,
    DESKTOP_AUTH_CREDENTIAL_MARKERS,
    getDesktopAuthenticatedAccessToken,
    getDesktopAuthenticatedRefreshToken,
    getDesktopAuthenticatedSession,
    getDesktopAuthenticatedSessionSnapshot,
    getDesktopAuthenticatedUserId,
    publishDesktopApiCredentials,
    publishDesktopAuthenticatedSession,
    requireDesktopAuthenticatedAccessToken,
    type DesktopAuthenticatedSessionSnapshot,
} from "./desktop-authenticated-session";
