/** DESKTOP ONLY — compatibility re-exports for the unified auth bootstrap flow. */

export {
    canRenderDesktopApplicationShell,
    createDesktopAuthBootstrapWatchdog,
    DESKTOP_AUTH_RATE_LIMIT_MESSAGE,
    DESKTOP_AUTH_SHELL_WATCHDOG_MS,
    DESKTOP_BOOTSTRAP_LOG_PREFIX,
    diagnoseDesktopShellGate,
    ensureDesktopAuthenticatedSession,
    forceDesktopAuthBootstrapShellReady,
    isDesktopAuthenticatedShellReady,
    isDesktopAuthSessionBootstrapComplete,
    isDesktopAuthSessionBootstrapSettled,
    isDesktopAuthShellWatchdogForced,
    markDesktopAuthSignInPending,
    resetDesktopAuthSessionBootstrap,
    runDesktopRemoteBootstrap,
    startDesktopAuthSessionBootstrap,
    startDesktopLocalBootstrap,
    traceBootstrapStep,
    waitForDesktopAuthenticatedSession,
    type DesktopAuthBootstrapConfig,
    type DesktopAuthBootstrapOutcome,
    type DesktopAuthSessionBootstrapOptions,
    type DesktopBootstrapStep,
    type DesktopRemoteBootstrapActions,
    type DesktopRemoteBootstrapResult,
    type DesktopShellGateDecision,
    type DesktopShellGateInput,
} from "./desktop-auth-bootstrap-flow";
