/** @deprecated Re-exports — use lib/desktop-protected-action-pipeline.ts */

export {
    acquireFreshDesktopProtectedCredentials,
    assertDesktopRelativeApiPath,
    createDesktopAuthBootstrapRuntime,
    createDesktopAuthenticatedFetch,
    createDesktopProtectedActionClient,
    createDesktopProtectedActionFetch,
    createDesktopProtectedActionPipeline,
    createDesktopProtectedApiFetch,
    createDesktopProtectedApiRuntime,
    DESKTOP_PROTECTED_ACTION_HEADER_TOO_LARGE_STATUS,
    DESKTOP_PROTECTED_API_LOGIN_REQUIRED_MESSAGE,
    DESKTOP_PROTECTED_API_SESSION_MESSAGE,
    DESKTOP_PROTECTED_ENDPOINTS,
    DESKTOP_PROTECTED_LIBRARY_API_PATHS,
    executeDesktopProtectedRequest,
    hasValidDesktopSupabaseSession,
    hydrateSupabaseClientFromStorage,
    resolveDesktopAuthenticatedCredentials,
    resolveDesktopProtectedApiCredentials,
    resolveLiveDesktopProtectedActionCredentials,
    resolveLiveProtectedApiSession,
    waitForDesktopApiCredentials,
    type DesktopAuthBootstrapConfig,
    type DesktopAuthenticatedCredentials,
    type DesktopAuthenticatedFetch,
    type DesktopAuthenticatedFetchInit,
    type DesktopAuthenticatedRequestConfig,
    type DesktopAuthTransport,
    type DesktopProtectedActionClientConfig,
    type DesktopProtectedActionCredentials,
    type DesktopProtectedActionFetch,
    type DesktopProtectedActionFetchInit,
    type DesktopProtectedActionPipelineConfig,
    type DesktopProtectedApiCredentials,
    type DesktopProtectedApiFetch,
    type DesktopProtectedApiFetchInit,
    type DesktopProtectedApiPipelineConfig,
} from "./desktop-protected-action-pipeline";
