export const REQUIRED_LAUNCH_TABLES = [
  "profiles",
  "user_roles",
  "artist_profiles",
  "producer_profiles",
  "producer_beats",
  "songs",
  "song_likes",
  "videos",
  "video_likes",
  "albums",
  "album_items",
  "playlists",
  "playlist_items",
  "library_saves",
  "artist_follows",
  "notifications",
  "content_comments",
  "comment_likes",
  "profile_verifications",
  "subscriptions",
  "subscription_plans",
  "transactions",
  "payouts",
  "revenue_splits",
  "earnings_events",
  "monthly_statements",
  "premium_content_access",
  "sales_cart_items",
  "purchase_history",
  "download_vault",
  "license_records",
  "marketplace_storefront_settings",
  "marketplace_featured_placements",
  "marketplace_discount_codes",
  "marketplace_bundles",
  "marketplace_bundle_items",
  "platform_errors",
  "launch_checklist",
  "storage_policy_audits",
  "storage_cleanup_delete_logs",
  "backup_exports",
  "moderation_reports",
  "copyright_claims",
  "blocked_users",
  "verification_review_requests",
  "support_tickets",
  "support_ticket_messages",
  "platform_incidents",
  "release_notes",
  "user_feedback",
  "ringtone_products",
  "ringtone_purchases",
  "ringtone_downloads",
  "ringtone_favorites",
  "ringtone_reviews",
];

export const EXPECTED_STORAGE_BUCKETS = [
  "songs",
  "videos",
  "covers",
  "albums",
  "producer-beats",
  "licenses",
  "downloads",
  "ringtone-source",
  "ringtone-previews",
  "ringtone-downloads",
];

export const PUBLIC_LAUNCH_ROUTES = [
  {
    name: "Public artist profile pages",
    path: "/artist/[id]",
    message: "Dynamic artist profile route and social metadata are configured.",
  },
  {
    name: "Public producer profile pages",
    path: "/producer/[id]",
    message: "Dynamic producer profile route and social metadata are configured.",
  },
  {
    name: "Main app SEO metadata",
    path: "/",
    message: "Root Open Graph and Twitter preview metadata are configured.",
  },
] as const;

export const DEFAULT_LAUNCH_CHECKLIST = [
  {
    area: "Security/RLS audit",
    status: "pending",
    details: "Confirm every public/private table has intentional policies.",
  },
  {
    area: "User roles and admin permissions",
    status: "pending",
    details: "Confirm admin-only routes and dashboards are guarded server-side.",
  },
  {
    area: "Production environment setup",
    status: "pending",
    details: "Confirm production env vars, auth redirects, and domain settings.",
  },
  {
    area: "Storage bucket policy audit",
    status: "pending",
    details: "Confirm media upload, playback, premium download, and cleanup policies.",
  },
  {
    area: "Error handling and loading states",
    status: "pending",
    details: "Confirm no blank states or production-impacting overlays.",
  },
  {
    area: "Mobile responsive polish",
    status: "pending",
    details: "Confirm mobile, tablet, laptop, and desktop layouts.",
  },
  {
    area: "Public artist/producer profile pages",
    status: "pending",
    details: "Confirm public profile URLs, metadata, and share previews.",
  },
  {
    area: "SEO/social share previews",
    status: "pending",
    details: "Confirm Open Graph and Twitter card metadata.",
  },
  {
    area: "Backup/export routine",
    status: "pending",
    details: "Confirm backup/export route and admin usage.",
  },
  {
    area: "Final launch checklist",
    status: "pending",
    details: "Run final lint, build, API, upload, playback, and dashboard checks.",
  },
  {
    area: "API smoke checks",
    status: "pending",
    details: "Confirm launch, media, library, playlist, sales, license, discovery, and recommendation APIs return 200.",
  },
  {
    area: "Marketplace and licensing launch QA",
    status: "pending",
    details: "Confirm marketplace, cart, purchase history, license records, and download vault foundations load.",
  },
  {
    area: "Trust and support operations",
    status: "pending",
    details: "Confirm reports, claims, verification review, tickets, incidents, release notes, and feedback are ready.",
  },
  {
    area: "Public profile sharing QA",
    status: "pending",
    details: "Confirm artist and producer public URLs render and share with the correct preview metadata.",
  },
] as const;
